---

- name: Add key {{ item.key }}
  apt_key: id={{ item.key.id }} keyserver={{ item.key.server }}
  when: item.key is defined

- name: Add apt repository {{ item.repo }}
  apt_repository: repo={{ item.repo }} state=present
  when: item.repo is defined

- name: Update apt
  apt: update_cache=yes
  when: item.repo is defined

- name: Install packages from repository
  apt: name={{ item.name }} state=present
  with_items: '{{item.packages}}'
  when: item.packages is defined

- name: Remove apt repository {{ item.repo }}
  apt_repository: repo='deb {{ item.repo }}' state=absent
  when: item.remove_repo is defined

- name: Install {{ item.deb }}
  apt: 'deb={{ item.deb }}'
  when: item.deb is defined

- name: Download {{ item.sh_url }}
  get_url: url={{ item.sh_url }} dest={{ item.sh_path }}
  when: item.sh_url is defined

- name: Run {{ item.sh_path }}
  shell: '{{ item.sh_path }}'
  when: item.sh_path is defined

- name: Download {{ item.remote_archive_to_desktop }}
  get_url: url={{ item.remote_archive_to_desktop }} dest={{ config.user.desktop_dir }}
  when: item.remote_archive_to_desktop is defined
